'use client';

import { FormEvent, useEffect, useState } from 'react';
import { apiBaseUrl } from '@/lib/rbac';

const field = 'w-full border-b border-[#2a2723]/20 bg-transparent px-1 py-3 text-sm outline-none focus:border-[#b8894d]';

export default function FeedbackPage({ params }: { params: Promise<{ token: string }> }) {
  const [token, setToken] = useState(''); const [orderNumber, setOrderNumber] = useState(''); const [error, setError] = useState(''); const [sent, setSent] = useState(false); const [ratings, setRatings] = useState<Record<string, number>>({}); const [answers, setAnswers] = useState({ loved: '', improve: '', wouldPurchase: '', comments: '' });
  useEffect(() => { params.then(({ token: value }) => { setToken(value); void fetch(`${apiBaseUrl}/api/feedback/${value}`).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setOrderNumber(payload.feedback.orderNumber || ''); }).catch((reason) => setError(reason instanceof Error ? reason.message : 'This link is no longer available.')); }); }, [params]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); const response = await fetch(`${apiBaseUrl}/api/feedback/${token}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...ratings, ...answers }) }); const payload = await response.json(); if (!response.ok) { setError(payload.error || 'Unable to submit feedback.'); return; } setSent(true); };
  if (sent) return <main className="min-h-screen bg-[#f8f5ef] px-6 py-24 text-center text-[#2a2723]"><p className="text-[10px] uppercase tracking-[.35em] text-[#b8894d]">Rashi Kapoor</p><h1 className="mt-5 font-serif text-5xl font-normal">Thank you.</h1><p className="mx-auto mt-5 max-w-md text-sm leading-7 text-[#716a61]">Your thoughts have been shared with the Rashi Kapoor team.</p></main>;
  return <main className="min-h-screen bg-[#f8f5ef] px-6 py-16 text-[#2a2723] sm:px-10"><div className="mx-auto max-w-2xl"><p className="text-[10px] uppercase tracking-[.35em] text-[#b8894d]">Rashi Kapoor · Your experience</p><h1 className="mt-5 font-serif text-5xl font-normal">How was your experience?</h1>{orderNumber ? <p className="mt-4 text-sm text-[#716a61]">Order #{orderNumber}</p> : null}{error ? <p className="mt-5 text-sm text-red-700">{error}</p> : null}<form onSubmit={submit} className="mt-12 space-y-10">{[['overall', 'Overall experience'], ['product', 'The product'], ['fit', 'The fit'], ['delivery', 'The delivery']].map(([key, label]) => <fieldset key={key}><legend className="text-[10px] uppercase tracking-[.22em] text-[#716a61]">{label}</legend><div className="mt-4 flex gap-2">{[1, 2, 3, 4, 5].map((value) => <button type="button" key={value} onClick={() => setRatings((current) => ({ ...current, [key]: value }))} className={`grid h-10 w-10 place-items-center rounded-full border text-sm ${ratings[key] === value ? 'border-[#b8894d] bg-[#b8894d] text-white' : 'border-black/15'}`}>{value}</button>)}</div></fieldset>)}<label className="block text-[10px] uppercase tracking-[.22em] text-[#716a61]">What did you love?<textarea value={answers.loved} onChange={(event) => setAnswers((current) => ({ ...current, loved: event.target.value }))} className={`${field} mt-2`} rows={3} /></label><label className="block text-[10px] uppercase tracking-[.22em] text-[#716a61]">What could we improve?<textarea value={answers.improve} onChange={(event) => setAnswers((current) => ({ ...current, improve: event.target.value }))} className={`${field} mt-2`} rows={3} /></label><fieldset><legend className="text-[10px] uppercase tracking-[.22em] text-[#716a61]">Would you purchase from RK again?</legend><div className="mt-3 flex gap-6 text-sm"><label><input type="radio" name="wouldPurchase" value="Yes" checked={answers.wouldPurchase === 'Yes'} onChange={(event) => setAnswers((current) => ({ ...current, wouldPurchase: event.target.value }))} /> <span className="ml-2">Yes</span></label><label><input type="radio" name="wouldPurchase" value="No" checked={answers.wouldPurchase === 'No'} onChange={(event) => setAnswers((current) => ({ ...current, wouldPurchase: event.target.value }))} /> <span className="ml-2">No</span></label></div></fieldset><label className="block text-[10px] uppercase tracking-[.22em] text-[#716a61]">Additional comments<textarea value={answers.comments} onChange={(event) => setAnswers((current) => ({ ...current, comments: event.target.value }))} className={`${field} mt-2`} rows={4} /></label><button className="bg-[#24211e] px-7 py-4 text-[10px] uppercase tracking-[.25em] text-white">Submit feedback</button></form></div></main>;
}
