'use client';

import { FormEvent, useEffect, useState } from 'react';
import { apiBaseUrl } from '@/lib/rbac';

export default function ReturnShipmentPage({ params }: { params: Promise<{ token: string }> }) {
  const [token, setToken] = useState(''); const [orderNumber, setOrderNumber] = useState(''); const [error, setError] = useState(''); const [sent, setSent] = useState(false); const [form, setForm] = useState({ courier: '', lrNumber: '', dispatchDate: '', note: '' });
  useEffect(() => { params.then(({ token: value }) => { setToken(value); void fetch(`${apiBaseUrl}/api/returns/${value}`).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setOrderNumber(payload.return.orderNumber || ''); }).catch((reason) => setError(reason instanceof Error ? reason.message : 'This link is no longer available.')); }); }, [params]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); const response = await fetch(`${apiBaseUrl}/api/returns/${token}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const payload = await response.json(); if (!response.ok) { setError(payload.error || 'Unable to submit return details.'); return; } setSent(true); };
  if (sent) return <main className="min-h-screen bg-[#f8f5ef] px-6 py-24 text-center text-[#2a2723]"><p className="text-[10px] uppercase tracking-[.35em] text-[#b8894d]">Rashi Kapoor</p><h1 className="mt-5 font-serif text-5xl font-normal">Details received.</h1><p className="mx-auto mt-5 max-w-md text-sm leading-7 text-[#716a61]">The RK team will review your return shipment information.</p></main>;
  return <main className="min-h-screen bg-[#f8f5ef] px-6 py-16 text-[#2a2723] sm:px-10"><div className="mx-auto max-w-xl"><p className="text-[10px] uppercase tracking-[.35em] text-[#b8894d]">Rashi Kapoor · Return shipment</p><h1 className="mt-5 font-serif text-5xl font-normal">Return shipment details</h1><p className="mt-4 text-sm text-[#716a61]">Order #{orderNumber}</p>{error ? <p className="mt-5 text-sm text-red-700">{error}</p> : null}<form onSubmit={submit} className="mt-12 space-y-7"><label className="block text-[10px] uppercase tracking-[.22em] text-[#716a61]">Courier name<input required value={form.courier} onChange={(event) => setForm((current) => ({ ...current, courier: event.target.value }))} className="mt-2 w-full border-b border-black/20 bg-transparent px-1 py-3 text-sm outline-none" /></label><label className="block text-[10px] uppercase tracking-[.22em] text-[#716a61]">LR number<input required value={form.lrNumber} onChange={(event) => setForm((current) => ({ ...current, lrNumber: event.target.value }))} className="mt-2 w-full border-b border-black/20 bg-transparent px-1 py-3 text-sm outline-none" /></label><label className="block text-[10px] uppercase tracking-[.22em] text-[#716a61]">Pickup / dispatch date<input type="date" value={form.dispatchDate} onChange={(event) => setForm((current) => ({ ...current, dispatchDate: event.target.value }))} className="mt-2 w-full border-b border-black/20 bg-transparent px-1 py-3 text-sm outline-none" /></label><label className="block text-[10px] uppercase tracking-[.22em] text-[#716a61]">Additional note<textarea value={form.note} onChange={(event) => setForm((current) => ({ ...current, note: event.target.value }))} rows={4} className="mt-2 w-full border-b border-black/20 bg-transparent px-1 py-3 text-sm outline-none" /></label><button className="bg-[#24211e] px-7 py-4 text-[10px] uppercase tracking-[.25em] text-white">Submit return details</button></form></div></main>;
}
