import type { LegalSection } from '@/components/site/legal-page';

export const legalPages: Record<string, { title: string; intro: string; sections: LegalSection[] }> = {
  privacy: { title: 'Privacy Policy', intro: 'How we collect, use, and protect information when you visit or use the Rashi Kapoor website.', sections: [
    ['Introduction', 'This policy explains how [COMPANY LEGAL NAME] handles information connected with this website and its services. Please replace the editable placeholders before publication.'],
    ['Information We Collect', 'Depending on how you use the website, information may include account details, contact information, order details, communications, device information, and technical usage data.'],
    ['How We Use Information', 'Information may be used to provide the website and services, process requests, communicate with you, improve the experience, maintain security, and meet legal obligations.'],
    ['Account Information', 'Account information is used to provide authenticated features and manage your preferences. Keep your credentials private and contact [PRIVACY EMAIL] if you suspect unauthorised access.'],
    ['Orders & Payments', 'Order and payment information is used to fulfil purchases and provide support. Payment details should be handled by the payment service selected at checkout; confirm the applicable provider before launch.'],
    ['Website Usage & Analytics', 'We may use technical and interaction data to understand performance and improve the website. Confirm the analytics tools and retention periods used by this deployment before publication.'],
    ['Cookies', 'Cookies and similar technologies may support essential functions, preferences, analytics, and communications. See the Cookies page for more information.'],
    ['Marketing Communications', 'Marketing messages are sent only where permitted and can be stopped using the unsubscribe option or by contacting [PRIVACY EMAIL].'],
    ['Sharing Information', 'Information may be shared with service providers who help operate the website, fulfil orders, or provide support, subject to appropriate instructions and safeguards.'],
    ['Data Security', 'We use reasonable administrative and technical measures appropriate to the information handled. No online service can guarantee absolute security.'],
    ['Data Retention', 'Information is retained only for as long as needed for the relevant purpose, legal obligations, dispute resolution, and legitimate business records.'],
    ['Your Rights', 'Depending on where you live, you may have rights to access, correct, delete, restrict, or object to certain processing. Contact [PRIVACY EMAIL] to make a request.'],
    ["Children's Privacy", 'The website is not directed to children. Contact [PRIVACY EMAIL] if you believe information was submitted by a child.'],
    ['Third-Party Services', 'Some website functions may rely on third-party services. Their own privacy policies apply to information they process.'],
    ['Policy Changes', 'We may update this policy when the website, services, or applicable requirements change. The date above will indicate the latest revision.'],
    ['Contact', 'Privacy questions can be sent to [PRIVACY EMAIL] or [BUSINESS ADDRESS].'],
  ].map(([title, body]) => ({ title, body })) },
  terms: { title: 'Terms & Conditions', intro: 'These Terms & Conditions govern your access to and use of our website, online services and purchase of products from us.', sections: [
    ['About Rashi Kapoor', 'Rashi Kapoor is an Indian luxury fashion label offering designer garments, occasion wear, Ready-to-Wear, Made-to-Order, customised and bespoke pieces. Many garments involve specialised craftsmanship, hand embroidery, embellishment, hand finishing, artisanal techniques and individual garment construction. Production, processing and delivery timelines may therefore vary depending on the product and individual order.'],
    ['Eligibility', 'You must be legally competent to enter into a contract under applicable law to place an order with us. Customers under 18 years of age may use our website only with the involvement and supervision of a parent or legal guardian.'],
    ['Product Information', 'We make reasonable efforts to ensure product descriptions, photographs, colours, measurements, materials, embroidery details and other information are accurate. Due to the handcrafted and artisanal nature of our products, minor variations may occur in colour, texture, embroidery, embellishment placement, weaving, dyeing, printing, finishing, measurements and fabric appearance. Such variations form part of handcrafted luxury garments and are not automatically defects. Colours may vary by screen, device, lighting and display settings. Styling elements, jewellery, footwear or accessories shown in photographs are not included unless specifically stated.'],
    ['Pricing', 'Prices may be displayed in INR, USD, EUR, GBP or other currencies depending on location, website settings or selected currency. The final payable price is displayed at checkout. Unless stated otherwise, prices may exclude shipping, customs or import duties, VAT, GST or equivalent taxes, local taxes, clearance or brokerage charges, customisation and destination-country charges. Prices may change without notice, but accepted orders are unaffected except for obvious pricing, technical or administrative errors. Refunds are generally made to the original payment method; exchange-rate fluctuations and bank or payment-provider fees remain outside Rashi Kapoor’s responsibility.'],
    ['Price Match', 'Rashi Kapoor does not guarantee the lowest available price. Any expressly offered price match requires an identical product, a publicly available price in the same geographical market, and a request before first payment. Private or unpublished prices do not qualify, and price matching cannot be combined with another discount. We may accept or decline a request at our discretion. Unless specifically stated, no general price-match programme operates.'],
    ['Order Placement', 'Placing an order is an offer to purchase. An automated confirmation acknowledges receipt but is not necessarily acceptance. Acceptance occurs when we confirm processing, production or dispatch. We may refuse or cancel where a product is unavailable, information is incomplete, payment cannot be verified, fraud is suspected, delivery is unavailable, an obvious error exists or circumstances beyond our control prevent fulfilment. Eligible amounts are refunded to the original payment method.'],
    ['Ready-to-Wear & Made-to-Order Production', 'Ready-to-Wear products are available for dispatch within approximately 3–4 weeks, subject to product availability. This is an estimated dispatch timeline and may vary because of order volume, quality checks, alterations, packaging, courier availability and circumstances beyond reasonable control. Made-to-Order products generally require approximately 7–8 weeks for production and dispatch. This estimated production timeline may vary because of fabric availability, embroidery or embellishment, hand craftsmanship, artisan availability, customisation, garment complexity, fittings, material sourcing, seasonal production and specialised techniques or materials. These are production and dispatch estimates, not guaranteed final delivery dates. Production begins after required payment and order details are confirmed.'],
    ['Customisation', 'Selected products may be customised subject to feasibility and availability, including measurement adjustments, colour changes, sleeve additions, coverage or length modifications and selected embroidery changes. Additional charges will be communicated before confirmation wherever reasonably possible. We may decline changes that are not technically, structurally or aesthetically feasible.'],
    ['Custom-Made & Bespoke Products', 'Made-to-measure, bespoke, personalised, non-standard-size and customer-modified garments, including garments made to supplied measurements or requiring special production, may be treated as custom-made. They are generally non-returnable, non-exchangeable and non-cancellable once production has commenced, subject to applicable law and statutory consumer rights.'],
    ['Measurements & Fitting', 'Customers must provide accurate measurements. We may request photographs, measurements or fitting details. The number of fittings depends on the garment and certain custom garments may require two or more. Changes after production to customer-supplied or approved measurements may be chargeable. Further alterations depend on feasibility, fabric, construction, charges, capacity and timeline.'],
    ['Cancellation by Customer', 'Request cancellation as soon as possible. It may be accepted only before production, customisation, alteration or dispatch. Once production or customisation starts, cancellation may no longer be possible. Approved refunds generally return to the original payment method and may take approximately 5–7 working days after approval, subject to banking and provider times. No cash refunds are provided. Further restrictions may apply to discounted, promotional, customised, personalised, Made-to-Order or bespoke products. Statutory rights remain unaffected.'],
    ['Cancellation by Rashi Kapoor', 'We may cancel an order where reasonably necessary because of product unavailability, pricing or technical errors, payment verification, suspected fraud, delivery limitations, material or production limitations, or events beyond reasonable control. Eligible paid amounts will be refunded to the original payment method.'],
    ['Returns & Exchanges', 'Eligible Ready-to-Wear products may be returned or exchanged subject to the Returns & Exchanges Policy. Made-to-Order products are generally non-returnable and non-exchangeable once production has commenced. Customised and bespoke products are generally non-returnable, non-exchangeable and non-cancellable once production has commenced. Customer-requested altered garments may be non-returnable and non-exchangeable. Applicable statutory rights and remedies are not limited.'],
    ['Defective, Damaged or Incorrect Products', 'Contact us as soon as possible if a product appears damaged, defective, incorrect or materially different from the product ordered, with order details and photographs or video. We may request evidence and, following verification, may offer repair, replacement, exchange or refund subject to applicable law.'],
    ['Alterations', 'Alterations requested after delivery may be chargeable. Further alterations resulting from changed preference, body measurements or incorrect customer measurements may be chargeable. Alterations outside India may face additional charges and logistical limits. Timelines depend on construction, workload and material availability.'],
    ['Payment', 'Orders must be paid in full before production unless agreed otherwise in writing. Authorised third-party gateways may process payments, and orders may undergo payment or fraud verification. We do not request passwords, card PINs, CVV numbers or OTPs through email, social media or support channels.'],
    ['Shipping & Delivery', 'Rashi Kapoor ships to selected destinations worldwide. Ready-to-Wear dispatch is approximately 3–4 weeks and Made-to-Order production and dispatch approximately 7–8 weeks. Shipping transit begins only after dispatch. Delivery varies by product, destination, courier, customs, local regulations, weather, public holidays and circumstances beyond reasonable control. Any delivery estimate is not an absolute guarantee.'],
    ['International Orders', 'International availability depends on destination. Orders may incur import or customs duties, VAT, GST or equivalent taxes, local taxes, clearance, brokerage, handling or other destination-country charges. Unless checkout states otherwise, these are the customer’s responsibility. Rashi Kapoor is not responsible for customs or authority delays.'],
    ['Customs & Import Requirements', 'Customers must ensure lawful import and provide accurate clearance information. Shipments held, delayed, returned or abandoned because of customs requirements, prohibited imports, unpaid charges, refusal or incorrect customer information may incur additional charges and, where law permits, may not qualify for a full refund.'],
    ['Delivery Address', 'Customers must provide a complete and accurate address, postal code, telephone number and email. We are not responsible for failure caused by incorrect or incomplete details, an unavailable recipient, refusal, or unpaid customs charges. Returned parcels may require additional re-dispatch charges.'],
    ['Split Shipments', 'Products with different production or availability timelines may be dispatched separately. Any additional charge for a customer-requested split shipment may be communicated before dispatch.'],
    ['Force Majeure', 'Rashi Kapoor is not responsible for delay or failure caused by circumstances beyond reasonable control, including natural disasters, flood, fire, epidemics, government restrictions, war, civil disturbance, strikes, transport or courier disruption, customs restrictions, material shortages, or artisan and production disruption.'],
    ['Intellectual Property', 'The Rashi Kapoor brand, logo, monogram, collection and garment designs, artwork, photographs, videos, graphics, website design, written content, lookbooks, sketches and technical drawings belong to or are licensed to Rashi Kapoor or the relevant rights holder. They may not be copied, modified, distributed, scraped or commercially exploited without written permission. Purchasing a garment does not transfer design rights.'],
    ['Website Use', 'You must not seek unauthorised access, interfere with security, scrape content with automated systems, copy the catalogue or designs commercially, impersonate another person, use the website unlawfully, or reproduce and exploit intellectual property without permission.'],
    ['Third-Party Services', 'The website may use payment gateways, couriers, logistics, hosting, analytics and other technology providers. Rashi Kapoor is not responsible for their independent policies, availability or practices.'],
    ['Limitation of Liability', 'To the maximum extent permitted by law, Rashi Kapoor is not liable for indirect, incidental, special or consequential losses arising from the website, delays, third-party services or products. Nothing excludes liability or consumer rights that cannot legally be excluded or limited.'],
    ['Indemnity', 'To the extent permitted by law, you agree to indemnify Rashi Kapoor, its directors, employees, representatives, agents and authorised providers against claims, losses, liabilities or expenses arising from unlawful website use, violation of these Terms, misuse of products or services, or infringement of another person’s rights.'],
    ['Privacy', 'Personal information will be handled according to our Privacy Policy, which explains how information is collected, used, stored and protected.'],
    ['Changes to Terms', 'These Terms may be updated from time to time and the revised version will carry a new Last Updated date. The Terms applying to an order are generally those in effect when it is accepted, unless law requires otherwise.'],
    ['Governing Law', 'These Terms are governed by the laws of India. Subject to consumer-protection laws, disputes are subject to the competent courts in [CITY, STATE], INDIA.'],
    ['Grievance Redressal', 'Grievance Officer: [NAME]. Designation: Grievance Officer. Email: [EMAIL]. Phone: [PHONE]. Registered Office: [ADDRESS]. Working Hours: [DAYS / HOURS]. Grievances will be handled according to applicable law.'],
    ['Contact', 'RASHI KAPOOR — [LEGAL ENTITY NAME], [REGISTERED OFFICE ADDRESS], India. Email: [CUSTOMER CARE EMAIL]. Phone: [CUSTOMER CARE PHONE]. GSTIN: [GSTIN]. CIN: [CIN, IF APPLICABLE].'],
  ].map(([title, body]) => ({ title, body })) },
  shippingDelivery: { title: 'Shipping & Delivery', intro: 'Production, dispatch and delivery information for Rashi Kapoor orders.', sections: [
    ['Ready-to-Wear', 'Ready-to-Wear products are available for dispatch within approximately 3–4 weeks, subject to product availability. This is an estimated dispatch timeline and may vary because of order volume, quality checks, alterations, packaging, courier availability and circumstances beyond reasonable control.'],
    ['Made-to-Order', 'Made-to-Order products generally require approximately 7–8 weeks for production and dispatch. Timelines may vary because of fabric availability, embroidery or embellishment, hand craftsmanship, artisan availability, customisation, garment complexity, fittings, material sourcing, seasonal production and specialised techniques or materials.'],
    ['Shipping Transit', 'Production and shipping transit are separate. Transit begins after dispatch and varies by destination, courier, customs, local regulations, weather, public holidays and circumstances beyond reasonable control. Delivery estimates are not absolute guarantees.'],
    ['Delivery Address', 'Customers are responsible for complete and accurate address and contact information. Incorrect or incomplete details, recipient unavailability, refusal of delivery or failure to pay customs charges may cause failure or additional re-dispatch charges.'],
    ['Split Shipments', 'Orders containing products with different timelines may be dispatched separately. Additional charges for a requested split shipment may be communicated before dispatch.'],
  ].map(([title, body]) => ({ title, body })) },
  returnsExchanges: { title: 'Returns & Exchanges', intro: 'Eligibility depends on how each garment was produced or altered.', sections: [
    ['Ready-to-Wear', 'Eligible Ready-to-Wear products may be returned or exchanged subject to this Returns & Exchanges Policy.'],
    ['Made-to-Order', 'Made-to-Order products are generally non-returnable and non-exchangeable once production has commenced, unless applicable law requires otherwise.'],
    ['Customised & Bespoke', 'Customised and bespoke products are generally non-returnable, non-exchangeable and non-cancellable once production has commenced, subject to applicable law.'],
    ['Altered Garments', 'Garments altered at the customer’s request may be non-returnable and non-exchangeable.'],
    ['Statutory Rights', 'Nothing in this policy limits consumer rights or statutory remedies that cannot legally be excluded.'],
  ].map(([title, body]) => ({ title, body })) },
  cancellation: { title: 'Cancellation Policy', intro: 'Cancellation depends on whether production, customisation, alteration or dispatch has begun.', sections: [
    ['Customer Cancellation', 'Requests must be made as soon as possible and may be accepted only before production, customisation, alteration or dispatch. Once production or customisation starts, cancellation may no longer be possible.'],
    ['Refunds', 'Approved eligible refunds generally return to the original payment method and may take approximately 5–7 working days after approval, subject to banking and payment-provider times. No cash refunds are provided.'],
    ['Restricted Products', 'Additional restrictions may apply to discounted, promotional, customised, personalised, Made-to-Order and bespoke products. Statutory cancellation rights that cannot be excluded remain unaffected.'],
    ['Cancellation by Rashi Kapoor', 'We may cancel where reasonably necessary because of unavailability, pricing or technical errors, payment verification, suspected fraud, delivery limitations, material or production limitations, or events beyond reasonable control. Eligible paid amounts will be refunded to the original payment method.'],
  ].map(([title, body]) => ({ title, body })) },
  customisationBespoke: { title: 'Customisation & Bespoke', intro: 'Selected garments may be customised, made to measure or produced as bespoke pieces.', sections: [
    ['Available Customisation', 'Subject to feasibility and availability, customisation may include measurement adjustments, colour changes, sleeve additions, coverage modifications, length modifications and selected embroidery changes.'],
    ['Feasibility & Charges', 'Additional charges will be communicated before confirmation wherever reasonably possible. We may decline a request that is not technically, structurally or aesthetically feasible.'],
    ['Custom-Made Products', 'Made-to-measure, bespoke, personalised, non-standard-size and customer-modified garments, including garments produced to customer measurements, may be treated as custom-made and are generally non-returnable, non-exchangeable and non-cancellable once production starts, subject to law.'],
    ['Measurements & Fittings', 'Customers must supply accurate measurements. Additional information, photographs or fittings may be required, and certain garments may require two or more fittings. Later fitting changes or alterations may be chargeable and depend on feasibility, fabric, construction, capacity and timeline.'],
  ].map(([title, body]) => ({ title, body })) },
  productDisclaimer: { title: 'Product Disclaimer', intro: 'Important information about handcrafted garments and product presentation.', sections: [
    ['Handcrafted Variations', 'Due to the handcrafted and artisanal nature of our products, minor variations may occur in colour, texture, embroidery, embellishment placement, weaving, dyeing, printing, finishing, measurements and fabric appearance. Such variations are part of the character of handcrafted luxury garments and are not automatically defects.'],
    ['Screen & Device Colour', 'Colours may appear different depending on screen, device, lighting and display settings.'],
    ['Styling Accessories', 'Product photographs may include styling elements, jewellery, footwear or accessories that are not included unless specifically stated.'],
  ].map(([title, body]) => ({ title, body })) },
  internationalOrders: { title: 'International Orders', intro: 'International ordering and customs responsibilities vary by destination.', sections: [
    ['Availability', 'International orders are accepted subject to delivery availability for the destination.'],
    ['Duties & Charges', 'Orders may incur import duties, customs duties, VAT, GST or equivalent taxes, local taxes, clearance charges, brokerage fees, handling charges and other destination-country charges. Unless checkout states otherwise, these are the customer’s responsibility.'],
    ['Import Requirements', 'Customers must ensure lawful import and provide accurate information required for customs clearance.'],
    ['Customs Delays & Returns', 'Rashi Kapoor is not responsible for customs or authority delays. Shipments held, delayed, returned or abandoned because of customs requirements, prohibited imports, unpaid charges, refusal or incorrect customer information may incur additional charges and, where law permits, may not qualify for a full refund.'],
  ].map(([title, body]) => ({ title, body })) },
  cookies: { title: 'Cookies', intro: 'A clear guide to the small technologies that help the website remember preferences and understand how it is used.', sections: ['What Cookies Are','Essential Cookies','Functional Cookies','Analytics Cookies','Marketing Cookies','Session Cookies','How Cookies Are Controlled','Browser Settings','Cookie Preferences','Third-Party Cookies'].map((title) => ({ title, body: `Cookies in this category may be used for ${title.toLowerCase()}. Confirm the exact cookies, providers, purposes, and retention periods used by this deployment before publication. You can manage available choices through your browser settings or the website's cookie preferences, where provided.` })) },
  shipping: { title: 'Shipping', intro: 'What happens after an order is placed, from confirmation and processing through delivery and tracking.', sections: ['Shipping Overview','Order Processing','Delivery','Tracking','Delays','International Orders','Address Changes','Contact'].map((title) => ({ title, body: `Information about ${title.toLowerCase()} is being prepared for publication. Please confirm the domestic and international timeframes, delivery areas, charges, customs, duties, taxes, address-change rules, and support contact at [CONTACT EMAIL] before launch.` })) },
  security: { title: 'Security', intro: 'How we approach protecting accounts, transactions, website connections, and customer information.', sections: ['Protecting Your Information','Account Security','Payment Security','Secure Connections','Data Protection','Staff Access','Security Monitoring','Report a Security Issue'].map((title) => ({ title, body: `Our approach to ${title.toLowerCase()} is based on reasonable access controls, careful handling, and ongoing review appropriate to the service. Do not infer a certification or specific technical standard from this general description. Report a concern to [SECURITY EMAIL].` })) },
};

const findLegalSection = (page: { sections: LegalSection[] }, title: string) => page.sections.find((section) => section.title === title) || { title, body: '' };
const termsSections = legalPages.terms;
const shippingSections = legalPages.shippingDelivery;
const returnsSections = legalPages.returnsExchanges;
const cancellationSections = legalPages.cancellation;
const internationalSections = legalPages.internationalOrders;

legalPages.shippingReturns = {
  title: 'Shipping & Returns',
  intro: 'Production, delivery, returns and cancellation information for Rashi Kapoor orders.',
  sections: [
    { title: 'Production & Dispatch', body: findLegalSection(termsSections, 'Ready-to-Wear & Made-to-Order Production').body },
    { title: 'Domestic Shipping', body: findLegalSection(termsSections, 'Shipping & Delivery').body },
    { title: 'International Shipping', body: `${findLegalSection(internationalSections, 'Availability').body} ${findLegalSection(termsSections, 'International Orders').body}` },
    { title: 'Customs & Duties', body: `${findLegalSection(internationalSections, 'Duties & Charges').body} ${findLegalSection(internationalSections, 'Import Requirements').body} ${findLegalSection(internationalSections, 'Customs Delays & Returns').body}` },
    { title: 'Returns & Exchanges', body: returnsSections.sections.map((section) => `${section.title}: ${section.body}`).join(' ') },
    { title: 'Cancellations', body: cancellationSections.sections.map((section) => `${section.title}: ${section.body}`).join(' ') },
    { title: 'Damaged / Incorrect Orders', body: findLegalSection(termsSections, 'Defective, Damaged or Incorrect Products').body },
    { title: 'Delivery Issues', body: `${findLegalSection(termsSections, 'Delivery Address').body} ${findLegalSection(termsSections, 'Split Shipments').body}` },
  ],
};

legalPages.legal = {
  title: 'Legal',
  intro: 'Terms, product information, customisation and legal notices for Rashi Kapoor.',
  sections: [
    { title: 'Terms & Conditions', body: ['About Rashi Kapoor', 'Eligibility', 'Pricing', 'Price Match', 'Order Placement', 'Website Use', 'Third-Party Services'].map((title) => `${title}: ${findLegalSection(termsSections, title).body}`).join(' ') },
    { title: 'Product Information & Disclaimer', body: `${findLegalSection(termsSections, 'Product Information').body} ${legalPages.productDisclaimer.sections.map((section) => section.body).join(' ')}` },
    { title: 'Customisation & Bespoke', body: `${legalPages.customisationBespoke.intro} ${legalPages.customisationBespoke.sections.map((section) => `${section.title}: ${section.body}`).join(' ')}` },
    { title: 'Measurements & Fittings', body: findLegalSection(termsSections, 'Measurements & Fitting').body },
    { title: 'Orders & Payments', body: `${findLegalSection(termsSections, 'Order Placement').body} ${findLegalSection(termsSections, 'Payment').body}` },
    { title: 'Shipping & Delivery', body: findLegalSection(termsSections, 'Shipping & Delivery').body },
    { title: 'Returns & Exchanges', body: findLegalSection(termsSections, 'Returns & Exchanges').body },
    { title: 'Cancellations', body: `${findLegalSection(termsSections, 'Cancellation by Customer').body} ${findLegalSection(termsSections, 'Cancellation by Rashi Kapoor').body}` },
    { title: 'International Orders', body: `${findLegalSection(termsSections, 'International Orders').body} ${findLegalSection(termsSections, 'Customs & Import Requirements').body}` },
    { title: 'Intellectual Property', body: findLegalSection(termsSections, 'Intellectual Property').body },
    { title: 'Liability & Indemnity', body: `${findLegalSection(termsSections, 'Limitation of Liability').body} ${findLegalSection(termsSections, 'Indemnity').body}` },
    { title: 'Governing Law', body: findLegalSection(termsSections, 'Governing Law').body },
    { title: 'Grievance Redressal', body: findLegalSection(termsSections, 'Grievance Redressal').body },
  ],
};
