import type { LegalSection } from '@/components/site/legal-page';

export const legalPages: Record<string, { title: string; intro: string; sections: LegalSection[] }> = {
  privacy: { title: 'Privacy Policy', intro: 'How we collect, use, and protect information when you visit or use the Rashi Kapoor website.', sections: [
    ['Introduction', 'This policy explains how [COMPANY LEGAL NAME] handles information connected with this website and its services. Please replace the editable placeholders before publication.'],
    ['Information We Collect', 'Depending on how you use the website, information may include account details, contact information, order details, communications, device information, and technical usage data.'],
    ['How We Use Information', 'Information may be used to provide the website and services, process requests, communicate with you, improve the experience, maintain security, and meet legal obligations.'],
    ['Account Information', 'Account information is used to provide authenticated features and manage your preferences. Keep your credentials private and contact [PRIVACY EMAIL] if you suspect unauthorised access.'],
    ['Orders & Payments', 'Order and payment information is used to fulfil purchases and provide support. Payment details should be handled by the payment service selected at checkout; confirm the applicable provider before launch.'],
    ['Website Usage & Analytics', 'We may use technical and interaction data to understand performance and improve the website. Confirm the analytics tools and retention periods used by this deployment before publication.'],
    ['Cookies', 'Cookies and similar technologies may support essential functions, preferences, analytics, and communications. See the Cookies page for more information.'],
    ['Marketing Communications', 'Marketing messages are sent only where permitted and can be stopped using the unsubscribe option or by contacting [PRIVACY EMAIL].'],
    ['Sharing Information', 'Information may be shared with service providers who help operate the website, fulfil orders, or provide support, subject to appropriate instructions and safeguards.'],
    ['Data Security', 'We use reasonable administrative and technical measures appropriate to the information handled. No online service can guarantee absolute security.'],
    ['Data Retention', 'Information is retained only for as long as needed for the relevant purpose, legal obligations, dispute resolution, and legitimate business records.'],
    ['Your Rights', 'Depending on where you live, you may have rights to access, correct, delete, restrict, or object to certain processing. Contact [PRIVACY EMAIL] to make a request.'],
    ["Children's Privacy", 'The website is not directed to children. Contact [PRIVACY EMAIL] if you believe information was submitted by a child.'],
    ['Third-Party Services', 'Some website functions may rely on third-party services. Their own privacy policies apply to information they process.'],
    ['Policy Changes', 'We may update this policy when the website, services, or applicable requirements change. The date above will indicate the latest revision.'],
    ['Contact', 'Privacy questions can be sent to [PRIVACY EMAIL] or [BUSINESS ADDRESS].'],
  ].map(([title, body]) => ({ title, body })) },
  terms: { title: 'Terms of Use', intro: 'The terms that apply when you browse, create an account, or use services provided through this website.', sections: ['Introduction','Eligibility','Accounts','Products','Product Images & Descriptions','Pricing','Orders','Payments','Shipping','Returns & Exchanges','Intellectual Property','User Content','Website Use','Third-Party Links','Limitation of Liability','Changes to Terms','Governing Law','Contact'].map((title) => ({ title, body: `This section is an editable working draft for ${title.toLowerCase()}. Confirm the final business rules, responsibilities, timeframes, and legal wording with [COMPANY LEGAL NAME] before publication. Where relevant, the applicable contact is [CONTACT EMAIL].` })) },
  cookies: { title: 'Cookies', intro: 'A clear guide to the small technologies that help the website remember preferences and understand how it is used.', sections: ['What Cookies Are','Essential Cookies','Functional Cookies','Analytics Cookies','Marketing Cookies','Session Cookies','How Cookies Are Controlled','Browser Settings','Cookie Preferences','Third-Party Cookies'].map((title) => ({ title, body: `Cookies in this category may be used for ${title.toLowerCase()}. Confirm the exact cookies, providers, purposes, and retention periods used by this deployment before publication. You can manage available choices through your browser settings or the website's cookie preferences, where provided.` })) },
  shipping: { title: 'Shipping', intro: 'What happens after an order is placed, from confirmation and processing through delivery and tracking.', sections: ['Shipping Overview','Order Processing','Delivery','Tracking','Delays','International Orders','Address Changes','Contact'].map((title) => ({ title, body: `Information about ${title.toLowerCase()} is being prepared for publication. Please confirm the domestic and international timeframes, delivery areas, charges, customs, duties, taxes, address-change rules, and support contact at [CONTACT EMAIL] before launch.` })) },
  security: { title: 'Security', intro: 'How we approach protecting accounts, transactions, website connections, and customer information.', sections: ['Protecting Your Information','Account Security','Payment Security','Secure Connections','Data Protection','Staff Access','Security Monitoring','Report a Security Issue'].map((title) => ({ title, body: `Our approach to ${title.toLowerCase()} is based on reasonable access controls, careful handling, and ongoing review appropriate to the service. Do not infer a certification or specific technical standard from this general description. Report a concern to [SECURITY EMAIL].` })) },
};
